VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('18')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('54')
MAJOR_VERSION = 0
MINOR_VERSION = 0
PATCH_VERSION = 202212180754
version_date = '2022/12/18 07:54'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
