VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('19')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('59')
MAJOR_VERSION = 0
MINOR_VERSION = 0
PATCH_VERSION = 202212190859
version_date = '2022/12/19 08:59'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
